### PR TITLE
Add Markdown Code Block Copy Functionality.

### PR DESCRIPTION
**Pull request by silverfantacy**
Add a copy button to the top-right corner of a Markdown code block.
image

### CODE REVIEW

**Comment by Jayyyu1w** [comment]
I found the button wont show until I refresh the page

Before refresh:
image
After refresh:
image

**Comment by silverfantacy** [comment]
@JoeyC-Dev fix

**Comment by silverfantacy** [comment]
@Jayyyu1w 
Not sure how astro is going to re-run the js on startup. 😢
Do you have any good ideas?

**Comment by JoeyC-Dev** [comment]
@silverfantacy Thank you. The latest commit does fix the issue.
Personally, I would like to add `opacity-75` for better view:
image
image

But it is up to you and the author of this repo. 
Appreciate your work again!

**Comment by silverfantacy** [comment]
@Jayyyu1w Fixed it, not sure if that's a good way to write it though.
@JoeyC-Dev add

**Comment by JoeyC-Dev** [comment]
@silverfantacy Thank you. It looks like the opacity will be forced changed to 100 again. I mean: it works initially but suddenly it changed to 100.
You can see the process when using F12 and enable throttling "Slow 3G".
I tried to delete `hover:opacity-100 transition-all duration-200` part and it looks like the root cause is not here. Deleting them not changes anything. So the `addPreCopyButton` fix breaks it.

**Comment by silverfantacy** [comment]
@JoeyC-Dev Sorry, I didn't understand what you meant. Could you provide more detailed explanation?
From my perspective, everything seems to be working fine even when I simulate a slow 3G connection. The opacity remains unchanged after 4 seconds.
The opacity is set to 100 during the hover event and when copying, and it returns to 75 once the event is over. This seems to be the intended behavior.

**Comment by JoeyC-Dev** [comment]
@silverfantacy What I meant is:
Even did not move the mice on the "copy" button, it will automatically change the opacity to 100.
I tested it on this deployment in incognito mode
https://fuwari-yags-1pa77mulo-zephyirdgmailcoms-projects.vercel.app/posts/markdown#an-h2-header 

I did not do anything but it is surely not transparent:
image
 
Same in edge:
image

**Comment by silverfantacy** [comment]
@JoeyC-Dev Thank you, I understand. I've fixed the bug

**Comment by JoeyC-Dev** [comment]
> @JoeyC-Dev Thank you, I understand. I've fixed the bug

Confirmed fixed. Thank you for your dedicated work again!
image

**Comment by saicaca** [comment]
Thank you for your contribution!

**Pull request merged**
