### PR TITLE
fix: fix publish draft blog in rss

### PR DESCRIPTION
**Pull request by CorrectRoadH**

### CODE REVIEW

**Comment by CorrectRoadH** [comment]
@saicaca Please take a look.

**Comment by CorrectRoadH** [comment]
This is urgent for me, mainly because I take the upstream priority policy, and I need to wait for this PR to enter the upstream before I can change the corresponding code on my blog.

**Comment by saicaca** [comment]
Thank you for your support but I believe this doesn't need a fix. The `getSortedPosts()` already excludes draft posts in production environment, they won't be listed in the built RSS file.

**Comment by CorrectRoadH** [comment]
> Thank you for your support but I believe this doesn't need a fix. The `getSortedPosts()` already excludes draft posts in production environment, they won't be listed in the built RSS file.

But what I see is that my draft appears in the RSS, but the blog page does not. I'll see what the reason is.🤔

**Comment by saicaca** [comment]
> But what I see is that my draft appears in the RSS, but the blog page does not.

This sounds strange. Both the page and the RSS use `getSortedPosts()` to retrieve the post list. They should share the same set of posts. 🤔

**Pull request closed without merging**
