### PR TITLE
Fix footer text

### PR DESCRIPTION
**Pull request by 3kh0**
This pull fixes the formatting of the footer.

Before

image

After

image

### CODE REVIEW

**Comment by 3kh0** [comment]
image

strange since the build works just fine on my machine as well as me testing it on cloudflare pages

**Comment by saicaca** [comment]
Thanks for your contribution! Could you please revert the changes to package.json and the lock file so we can avoid conflicts?

**Comment by 3kh0** [comment]
> Thanks for your contribution! Could you please revert the changes to package.json and the lock file so we can avoid conflicts?

Done :D

**Comment by saicaca** [comment]
Thank you!

**Pull request merged**
