### PR TITLE
Stop using corepack

### LINKED ISSUE #228: I want to stop using corepack.
Since it has been deprecated in Node.js Proposal, I would like to abolish it considering its future prospects. 
Personally, I would like to adopt [moonrepo/proto](https://moonrepo.dev/proto) as a candidate. 
Alternatively, the following method is also acceptable.
https://pnpm.io/only-allow-pnpm

https://github.com/saicaca/fuwari/blob/87547fca869840b8597199f5134bc1a873a4f5d5/package.json#L73

### PR DESCRIPTION
**Pull request by L4Ph**
close #228 
- Enforce the use of pnpm.
- Remove the reference to corepack from the package manager.
- Update the version of pnpm.

### CODE REVIEW

**Comment by L4Ph** [comment]
I think the settings on the Vercel side need to be corrected.
@saicaca

**Comment by saicaca** [comment]
It seems Vercel doesn't allow the use of `use-node-version` for some reason.
https://github.com/orgs/vercel/discussions/2436

 Would the [`engines`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) and [`pnpm.executionEnv.nodeVersion`](https://pnpm.io/package_json#pnpmexecutionenvnodeversion) serve the same purpose?

**Comment by L4Ph** [comment]
> It seems Vercel doesn't allow the use of `use-node-version` for some reason. https://github.com/orgs/vercel/discussions/2436
> 
> Would the [`engines`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) and [`pnpm.executionEnv.nodeVersion`](https://pnpm.io/package_json#pnpmexecutionenvnodeversion) serve the same purpose?

I think it's possible.
Change this from the original.

**Comment by L4Ph** [comment]
🤔

**Comment by L4Ph** [comment]
image

I tried deploying it with a Vercel account, but it passed normally...
I wonder what it is...

**Comment by saicaca** [comment]
```
 ERR_PNPM_INVALID_NODE_VERSION  "~22" is not a valid Node.js version
```

Maybe an exact version is needed🤔

**Comment by L4Ph** [comment]
Apparently there is no way to specify the node version in Vercel. (Also, it seems that it is not possible to make only Vercel be ignored.)

The commit has become too dirty, so I'll clean up the commit and submit another pull request.

**Pull request closed without merging**
