### PR TITLE
Added dynamic Github repository cards

### PR DESCRIPTION
**Pull request by Fabrizz**
### Card demo:
https://github.com/saicaca/fuwari/assets/65259076/65e65227-057a-4946-a68c-7e0f27f52526
> The part were the card is pressed and the color changes and is maintained like that for a second, is because I maintained the click so the animation can be seen in the video, the timing/transitions corresponds to the click action

### Markdown syntax:
```md
[!GITHUB user/repo]
[!GITHUB saicaca/fuwari]
```

### Smaller screens:
https://github.com/saicaca/fuwari/assets/65259076/c66b5775-dfaa-4fa3-ba62-826cdf0c0843

### Waiting for github
https://github.com/saicaca/fuwari/assets/65259076/eff3db11-2ed3-4d8d-8c8c-eaf72ab5e389

### CODE REVIEW

**Comment by saicaca** [comment]
Thanks for your contribution! This is a very useful feature.

But I would prefer to use the [remark-directive](https://github.com/remarkjs/remark-directive) to do this, following the [generic directive syntax](https://talk.commonmark.org/t/generic-directives-plugins-syntax/444). The syntax will look like:

```
::github{repo="user/repo"}
```

I would appreciate your help in implementing this, or you can leave it to me, and I will implement it when I have time.

**Comment by Fabrizz** [comment]
> Thanks for your contribution! This is a very useful feature.
> 
> But I would prefer to use the [remark-directive](https://github.com/remarkjs/remark-directive) to do this, following the [generic directive syntax](https://talk.commonmark.org/t/generic-directives-plugins-syntax/444). The syntax will look like:
> 
> ```
> ::github{repo="user/repo"}
> ```
> 
> I would appreciate your help in implementing this, or you can leave it to me, and I will implement it when I have time.

I will look at that, now that I read about it, using directives make more sense. I never used astro/# remark/rehype, a little new to me. I will look at this when I get some time as I really need to study for some exams

**Comment by Fabrizz** [comment]
For the [GFM admomitions](https://github.com/saicaca/fuwari/pull/68) should that also be converted to the generic directive syntax?

**Comment by saicaca** [comment]
> For the [GFM admomitions](https://github.com/saicaca/fuwari/pull/68) should that also be converted to the generic directive syntax?

Yes! I just left a comment there too.

**Comment by Fabrizz** [comment]
@saicaca Hey do you have any comment on the styling of the card?:

https://github.com/saicaca/fuwari/assets/65259076/12f83a30-a3cb-495c-9d1d-7ef318209662

**Comment by saicaca** [comment]
> @saicaca Hey do you have any comment on the styling of the card?:

This style looks good! You don’t need to worry too much about the styling; I will make further adjustments if necessary.😀

**Pull request closed without merging**
